import { useEffect, useState } from 'react';
import { commerceApi } from '../api/commerce';
import { EmptyState } from '../components/StateViews';

const initial = { label: 'Home', recipientName: '', line1: '', line2: '', city: '', state: '', postalCode: '', country: 'US', phone: '', isDefault: false };
export default function AddressesPage() {
  const [rows, setRows] = useState([]); const [form, setForm] = useState(initial); const [show, setShow] = useState(false); const [error, setError] = useState('');
  const load = () => commerceApi.addresses().then(setRows);
  useEffect(() => { load(); }, []);
  const submit = async (e) => { e.preventDefault(); setError(''); try { await commerceApi.addAddress(form); setForm(initial); setShow(false); load(); } catch (err) { setError(err.message); } };
  return <div className="page container"><div className="page-title-row"><div><span className="eyebrow dark">Delivery</span><h1>Saved addresses</h1><p>Checkout verifies address ownership through address-service.</p></div><button className="btn btn-primary" onClick={() => setShow(!show)}>{show ? 'Close form' : '+ Add address'}</button></div>{show && <form className="panel address-form" onSubmit={submit}>{error && <div className="form-error">{error}</div>}<div className="form-grid"><label>Label<input value={form.label} onChange={(e)=>setForm({...form,label:e.target.value})} /></label><label>Recipient<input required value={form.recipientName} onChange={(e)=>setForm({...form,recipientName:e.target.value})} /></label><label>Address line 1<input required value={form.line1} onChange={(e)=>setForm({...form,line1:e.target.value})} /></label><label>Address line 2<input value={form.line2} onChange={(e)=>setForm({...form,line2:e.target.value})} /></label><label>City<input required value={form.city} onChange={(e)=>setForm({...form,city:e.target.value})} /></label><label>State<input required value={form.state} onChange={(e)=>setForm({...form,state:e.target.value})} /></label><label>Postal code<input required value={form.postalCode} onChange={(e)=>setForm({...form,postalCode:e.target.value})} /></label><label>Country<input required value={form.country} onChange={(e)=>setForm({...form,country:e.target.value})} /></label><label>Phone<input value={form.phone} onChange={(e)=>setForm({...form,phone:e.target.value})} /></label><label className="checkbox"><input type="checkbox" checked={form.isDefault} onChange={(e)=>setForm({...form,isDefault:e.target.checked})} /> Make default</label></div><button className="btn btn-primary">Save address</button></form>}{rows.length ? <div className="address-grid">{rows.map((a) => <article className="address-card" key={a.id}><div><strong>{a.label}</strong>{a.is_default && <span className="default-badge">Default</span>}</div><h3>{a.recipient_name}</h3><p>{a.line1}{a.line2 ? `, ${a.line2}` : ''}<br />{a.city}, {a.state} {a.postal_code}<br />{a.country}</p><button className="link-button danger" onClick={() => commerceApi.removeAddress(a.id).then(load)}>Delete</button></article>)}</div> : !show && <EmptyState title="No address saved" text="Add an address before placing an order." />}</div>;
}
