import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { commerceApi, getProductBundle } from '../api/commerce';

const money = (v) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(v || 0));
export default function CheckoutPage() {
  const [addresses,setAddresses]=useState([]); const [cart,setCart]=useState([]); const [addressId,setAddressId]=useState(''); const [code,setCode]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const navigate=useNavigate();
  useEffect(()=>{Promise.all([commerceApi.addresses(),commerceApi.cart()]).then(async([a,c])=>{setAddresses(a);setAddressId(a.find(x=>x.is_default)?.id||a[0]?.id||'');setCart(await Promise.all((c.items||[]).map(async x=>({...x,bundle:await getProductBundle(x.product_id)}))))}).catch(e=>setError(e.message))},[]);
  const subtotal=useMemo(()=>cart.reduce((s,x)=>s+Number(x.bundle.price?.effective_price??x.bundle.price?.base_price??0)*Number(x.quantity),0),[cart]);
  const submit=async()=>{if(!addressId)return setError('Select or add a delivery address.');setBusy(true);setError('');try{const result=await commerceApi.checkout({addressId,promotionCode:code||undefined,currency:'USD',paymentMethod:{type:'card'}});navigate('/orders',{state:{checkoutResult:result}})}catch(e){setError(e.message)}finally{setBusy(false)}};
  return <div className="page container"><div className="page-title-row"><div><span className="eyebrow dark">Orchestration</span><h1>Checkout</h1><p>One request coordinates cart, pricing, promotion, fraud, inventory, payment, order, shipping, notifications and analytics.</p></div></div>{error&&<div className="form-error wide">{error}</div>}<div className="checkout-layout"><div><section className="panel checkout-section"><h2>1. Delivery address</h2>{addresses.length? <div className="radio-list">{addresses.map(a=><label className={`radio-card ${addressId===a.id?'selected':''}`} key={a.id}><input type="radio" name="address" checked={addressId===a.id} onChange={()=>setAddressId(a.id)} /><span><strong>{a.label} · {a.recipient_name}</strong><small>{a.line1}, {a.city}, {a.state} {a.postal_code}</small></span></label>)}</div>:<p>No addresses yet. <Link to="/addresses">Add one first.</Link></p>}</section><section className="panel checkout-section"><h2>2. Promotion</h2><label>Coupon code<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Optional promotion code" /></label></section><section className="panel checkout-section"><h2>3. Payment</h2><div className="payment-mock"><span>▣</span><div><strong>Mock card payment</strong><small>Phase 1 payment-service captures a simulated card payment.</small></div></div></section></div><aside className="summary-card sticky"><h2>Review order</h2>{cart.map(x=><div className="summary-line" key={x.product_id}><span>{x.bundle.product.name} × {x.quantity}</span><strong>{money(Number(x.bundle.price?.effective_price??x.bundle.price?.base_price??0)*Number(x.quantity))}</strong></div>)}<hr/><div className="summary-total"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><button className="btn btn-primary btn-large" disabled={busy||!cart.length} onClick={submit}>{busy?'Processing services…':'Place order'}</button></aside></div></div>;
}
