prometheus:
  enabled: true

  prometheusSpec:
    retention: 15d

    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

    resources:
      requests:
        cpu: 250m
        memory: 512Mi

      limits:
        cpu: "1"
        memory: 2Gi

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce

          resources:
            requests:
              storage: 20Gi


grafana:
  enabled: true

  service:
    type: ClusterIP

  persistence:
    enabled: true
    size: 10Gi


alertmanager:
  enabled: true

  alertmanagerSpec:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi

      limits:
        cpu: 500m
        memory: 512Mi


kube-state-metrics:
  enabled: true