apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: megamart
  labels:
    app: auth-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
        - name: auth-service
          image: AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/auth-service:latest
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 3001

          envFrom:
            - configMapRef:
                name: megamart-config
            - secretRef:
                name: megamart-secrets

          env:
            - name: PORT
              value: "3001"

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: megamart-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: megamart-secrets
                  key: POSTGRES_PASSWORD

            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/auth_db"

            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: megamart-secrets
                  key: RABBITMQ_USER

            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: megamart-secrets
                  key: RABBITMQ_PASSWORD

            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq:5672"

            - name: EVENT_EXCHANGE
              value: "megamart.events"

            - name: USER_SERVICE_URL
              value: "http://user-service:3002"

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20

          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi