apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: megamart

spec:
  replicas: 1

  selector:
    matchLabels:
      app: cart-service

  template:
    metadata:
      labels:
        app: cart-service

    spec:
      containers:
        - name: cart-service
          image: 047385030300.dkr.ecr.us-east-1.amazonaws.com/cart-service:latest

          ports:
            - name: http
              containerPort: 3006

          envFrom:
            - configMapRef:
                name: megamart-config
            - secretRef:
                name: megamart-secrets

          env:
            - name: PORT
              value: "3006"

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: megamart-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: megamart-secrets
                  key: POSTGRES_PASSWORD

            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/cart_db"

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
