apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service
  namespace: megamart

spec:
  replicas: 1

  selector:
    matchLabels:
      app: pricing-service

  template:
    metadata:
      labels:
        app: pricing-service

    spec:
      containers:
        - name: pricing-service
          image: AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/pricing-service:latest

          ports:
            - name: http
              containerPort: 3015

          envFrom:
            - configMapRef:
                name: megamart-config
            - secretRef:
                name: megamart-secrets

          env:
            - name: PORT
              value: "3015"

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: megamart-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: megamart-secrets
                  key: POSTGRES_PASSWORD

            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/pricing_db"

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10