apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-service
  namespace: megamart

spec:
  replicas: 1

  selector:
    matchLabels:
      app: wishlist-service

  template:
    metadata:
      labels:
        app: wishlist-service

    spec:
      containers:
        - name: wishlist-service
          image: 047385030300.dkr.ecr.us-east-1.amazonaws.com/wishlist-service:latest

          ports:
            - name: http
              containerPort: 3017

          envFrom:
            - configMapRef:
                name: megamart-config
            - secretRef:
                name: megamart-secrets

          env:
            - name: PORT
              value: "3017"

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: megamart-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: megamart-secrets
                  key: POSTGRES_PASSWORD

            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/wishlist_db"

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
