apiVersion: v1
kind: Service
metadata:
  name: address-service
  namespace: megamart
  labels:
    app: address-service
    monitoring: prometheus

spec:
  type: ClusterIP
  selector:
    app: address-service

  ports:
    - name: http
      port: 3018
      targetPort: http