apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: megamart
  labels:
    app: admin-service
    monitoring: prometheus

spec:
  type: ClusterIP
  selector:
    app: admin-service

  ports:
    - name: http
      port: 3021
      targetPort: http