apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: megamart
  labels:
    app: analytics-service
    monitoring: prometheus

spec:
  type: ClusterIP
  selector:
    app: analytics-service

  ports:
    - name: http
      port: 3023
      targetPort: http