apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: megamart
  labels:
    app: cart-service
    monitoring: prometheus

spec:
  type: ClusterIP
  selector:
    app: cart-service

  ports:
    - name: http
      port: 3006
      targetPort: http