apiVersion: v1
kind: Service
metadata:
  name: checkout-service
  namespace: megamart
  labels:
    app: checkout-service
    monitoring: prometheus

spec:
  type: ClusterIP
  selector:
    app: checkout-service

  ports:
    - name: http
      port: 3019
      targetPort: http