apiVersion: v1
kind: Service
metadata:
  name: fraud-service
  namespace: megamart
  labels:
    app: fraud-service
    monitoring: prometheus

spec:
  type: ClusterIP
  selector:
    app: fraud-service

  ports:
    - name: http
      port: 3024
      targetPort: http