apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: megamart
  labels:
    app: frontend

spec:
  type: ClusterIP

  selector:
    app: frontend

  ports:
    - name: http
      port: 80
      targetPort: http