apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: megamart
  labels:
    app: inventory-service
    monitoring: prometheus

spec:
  type: ClusterIP
  selector:
    app: inventory-service

  ports:
    - name: http
      port: 3005
      targetPort: http