apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: megamart
  labels:
    app: notification-service
    monitoring: prometheus

spec:
  type: ClusterIP
  selector:
    app: notification-service

  ports:
    - name: http
      port: 3010
      targetPort: http