apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: megamart
  labels:
    app: order-service
    monitoring: prometheus

spec:
  type: ClusterIP
  selector:
    app: order-service

  ports:
    - name: http
      port: 3007
      targetPort: http