apiVersion: v1
kind: Service
metadata:
  name: pricing-service
  namespace: megamart
  labels:
    app: pricing-service
    monitoring: prometheus

spec:
  type: ClusterIP
  selector:
    app: pricing-service

  ports:
    - name: http
      port: 3015
      targetPort: http