apiVersion: v1
kind: Service
metadata:
  name: promotion-service
  namespace: megamart
  labels:
    app: promotion-service
    monitoring: prometheus

spec:
  type: ClusterIP
  selector:
    app: promotion-service

  ports:
    - name: http
      port: 3016
      targetPort: http