apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: megamart
  labels:
    app: recommendation-service
    monitoring: prometheus

spec:
  type: ClusterIP
  selector:
    app: recommendation-service

  ports:
    - name: http
      port: 3014
      targetPort: http