apiVersion: v1
kind: Service
metadata:
  name: wishlist-service
  namespace: megamart
  labels:
    app: wishlist-service
    monitoring: prometheus

spec:
  type: ClusterIP
  selector:
    app: wishlist-service

  ports:
    - name: http
      port: 3017
      targetPort: http