apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-pvc
  namespace: megamart

  labels:
    app: postgres

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 20Gi