apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: rabbitmq-pvc
  namespace: megamart

  labels:
    app: rabbitmq

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi