apiVersion: v1
kind: Service

metadata:
  name: rabbitmq
  namespace: megamart

  labels:
    app: rabbitmq
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: megamart

spec:
  type: ClusterIP

  selector:
    app: rabbitmq

  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: amqp

    - name: management
      protocol: TCP
      port: 15672
      targetPort: management