apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: rabbitmq
  namespace: megamart

  labels:
    app: rabbitmq
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: megamart

spec:
  serviceName: rabbitmq

  replicas: 1

  selector:
    matchLabels:
      app: rabbitmq

  template:
    metadata:
      labels:
        app: rabbitmq
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/part-of: megamart

    spec:
      terminationGracePeriodSeconds: 60

      containers:
        - name: rabbitmq

          image: rabbitmq:4-management-alpine
          imagePullPolicy: IfNotPresent

          ports:
            - name: amqp
              containerPort: 5672
              protocol: TCP

            - name: management
              containerPort: 15672
              protocol: TCP

          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: megamart-secrets
                  key: RABBITMQ_USER

            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: megamart-secrets
                  key: RABBITMQ_PASSWORD

          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /var/lib/rabbitmq

          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping

            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10

          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping

            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5

          resources:
            requests:
              cpu: 200m
              memory: 256Mi

            limits:
              cpu: "1"
              memory: 1Gi

      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc