apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: redis
  namespace: megamart

  labels:
    app: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: megamart

spec:
  serviceName: redis

  replicas: 1

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: megamart

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: redis

          image: redis:7-alpine
          imagePullPolicy: IfNotPresent

          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP

          command:
            - redis-server
            - --appendonly
            - "yes"

          volumeMounts:
            - name: redis-storage
              mountPath: /data

          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping

            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping

            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi

      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc