apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: aws-load-balancer-controller
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://aws.github.io/eks-charts

    chart: aws-load-balancer-controller

    targetRevision: 1.14.0

    helm:
      releaseName: aws-load-balancer-controller

      values: |
        clusterName: megamart-dev

        region: us-east-1

        vpcId: vpc-0274ca55d5b49d289

        replicaCount: 2

        serviceAccount:
          create: true
          name: aws-load-balancer-controller

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - ServerSideApply=true