apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: monitoring
  namespace: argocd

spec:
  project: default

  sources:

    # --------------------------------------------------------
    # Prometheus Community Helm chart
    # --------------------------------------------------------

    - repoURL: https://prometheus-community.github.io/helm-charts

      chart: kube-prometheus-stack

      targetRevision: 87.21.0

      helm:
        releaseName: kube-prometheus-stack

        valueFiles:
          - $values/monitoring/prometheus-values.yaml


    # --------------------------------------------------------
    # Our Git repository containing prometheus-values.yaml
    # --------------------------------------------------------

    - repoURL: https://github.com/ziazeshan141/DevOps-microservices.git

      targetRevision: Test

      ref: values


  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring


  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true